### ISSUE TITLE
[docs] explain rest api url schema design

### ISSUE THREAD

**Issue by LeiYangGH** [igorbenav/fastcrud#143]
I tried both [fastapi-crudrouter](https://github.com/awtkns/fastapi-crudrouter) and `fastcrud`, and yes, `fastcrud` is actively maintained and support latest libraries versions, thank you!

but comparing the auto generated(default) api urls, I'm wondering why `fastcrud` not reuse the original `fastapi-crudrouter` api schema.

for example, 

## get all:

- fastapi-crudrouter
  model

- fastcrud 
  model/get_multi

## create

- fastapi-crudrouter
  model

- fastcrud 
  model/create

though url patterns can be customized, personally I think `fastapi-crudrouter` is more elegant(at least it requires less typing ^_^).

So could you add document section on the design thoughts?

**Comment by igorbenav** [comment]
Hey, @LeiYangGH, tbh I didn't know about fastapi-crudrouter until after I had almost released fastcrud, so it didn't inspire my design decisisons.

Since the EndpointCreator was - for me - a natural evolution of the FastCRUD class, I used the same urls for the endpoints as I used for the methods names.

Indeed I think the way fastapi-crudrouter does it is better, which is why @JakNowy fixed this [here](https://github.com/igorbenav/fastcrud/issues/67), for now we added a warning, but in 0.15 it will become the standard way. 

You can see the warning in the [docs here](https://igorbenav.github.io/fastcrud/advanced/endpoint/) or when you don't pass endpoint names when using `crud_router` or `EndpointCreator`.

Thanks for the question!

**Comment by LeiYangGH** [comment]
thanks! in fact i got to know fastcrud by your comments at [fastapi-crudrouter](https://github.com/awtkns/fastapi-crudrouter/issues/195). but i'm glad your version is actively maintained.
